# Generated by Django 5.2.3 on 2025-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id_bitacora_acceso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(max_length=35)),
                ('fecha_acceso', models.DateField()),
                ('resultado', models.CharField(max_length=35)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora_acceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraCanje',
            fields=[
                ('id_bitacora_canje', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('accion', models.CharField(max_length=35)),
                ('fecha_accion', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora_canje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraCatalogo',
            fields=[
                ('id_bitacora_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('accion', models.CharField(max_length=35)),
                ('fecha_accion', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora_catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraReciclaje',
            fields=[
                ('id_bitacora_reciclaje', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('accion', models.CharField(max_length=35)),
                ('fecha_accion', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanjeDonacion',
            fields=[
                ('id_canje_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=35)),
                ('fecha_canje', models.DateField()),
                ('puntos_descontados', models.IntegerField()),
            ],
            options={
                'db_table': 'canje_donacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id_canje_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=35)),
                ('fecha_canje', models.DateField()),
                ('puntos_descontados', models.IntegerField()),
            ],
            options={
                'db_table': 'canje_recompensa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoRecompensa',
            fields=[
                ('id_catalogo_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('puntos_coste', models.IntegerField()),
                ('disponible', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('categoria', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'catalogo_recompensa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('entidad_donacion', models.CharField(max_length=35)),
                ('monto_donacion', models.FloatField()),
            ],
            options={
                'db_table': 'donacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactoAmbientalDiario',
            fields=[
                ('id_impacto_ambiental_diario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_dia', models.DateField()),
                ('tipo_basura', models.CharField(max_length=35)),
                ('unidad_medida', models.CharField(max_length=10)),
                ('cantidad_reciclada_por_tipo', models.FloatField()),
                ('co2_reducido_por_tipo', models.FloatField()),
            ],
            options={
                'db_table': 'impacto_ambiental_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialPuntoReciclaje',
            fields=[
                ('pk', models.CompositePrimaryKey('id_material_reciclable', 'id_punto_reciclaje', blank=True, editable=False, primary_key=True, serialize=False)),
                ('condiciones_especificas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_punto_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialReciclable',
            fields=[
                ('id_material_reciclable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('puntos_por_unidad', models.IntegerField()),
                ('co2_por_unidad', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'material_reciclable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoReciclaje',
            fields=[
                ('id_punto_reciclaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('capacidad_maxima', models.IntegerField()),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('estado_punto', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'punto_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroReciclaje',
            fields=[
                ('id_registro_reciclaje', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_kg', models.FloatField()),
                ('puntos_obtenidos', models.IntegerField()),
                ('co2_reducido', models.FloatField()),
                ('fecha_registro', models.DateField()),
                ('nombre_subtipo', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'registro_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('pk', models.CompositePrimaryKey('id_rol', 'id_permiso', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('balance_puntos', models.IntegerField(default=0)),
                ('fecha_registro', models.DateField()),
                ('contraseña', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('id_rol', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
